Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -59,3 +59,13 @@ jobs:
         NOTIFY_ME_KEY_ALIAS: ${{ secrets.NOTIFY_ME_KEY_ALIAS }}
         NOTIFY_ME_KEY_PASSWORD: ${{ secrets.NOTIFY_ME_KEY_PASSWORD }}
         NOTIFY_ME_KEYSTORE_PASSWORD: ${{ secrets.NOTIFY_ME_KEYSTORE_PASSWORD }}
+
+    # Step 7: Find the generated APK and rename it with the tag name
+    - name: Find and Rename APK
+      run: |
+        APK_PATH=$(find app/build/outputs/apk/ -name "*.apk" | head -n 1)
+        if [ -z "$APK_PATH" ]; then
+          echo "APK not found"
+          exit 1
+        fi
+        mv "$APK_PATH" "app/build/outputs/apk/release/notify-me-${GITHUB_REF_NAME}.apk"
